# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2022 IBM Corporation
# Author: Nayna Jain <nayna@linux.ibm.com>
#
# Makefile for the firmware security filesystem

obj-$(CONFIG_FWSECURITYFS)		+= fwsecurityfs.o

fwsecurityfs-objs			:= super.o
